- name: monitoring catalogs
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: root
    group: root
  with_items:
    - { path: "/root/monitoring" }
    - { path: "/root/monitoring/etc" }
    - { path: "/root/monitoring/data" }
    - { path: "/root/monitoring/data/prom", mode: "0777" }
    - { path: "/root/monitoring/data/grafana", mode: "0777" }

- name: templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest  }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - { src: "docker-compose.yml.j2", dest: "/root/monitoring/docker-compose.yml" }
    - { src: "prometheus-config.yml.j2", dest: "/root/monitoring/etc/prometheus.yml" }
    - { src: ".env.j2", dest: "/root/monitoring/.env" }

- name: ensure compose running
  community.docker.docker_compose:
    project_src: /root/monitoring
    state: present
    restarted: yes
