- hosts: master
  tasks:
  - name: start web
    systemd: name=cs.web state=started
  - name: start manager
    systemd: name=cs.manager state=started
  - name: start worker
    systemd: name=cs.worker-default state=started
  - name: start watcher
    systemd: name=cs.watcher state=started

- hosts: flags
  tasks:
  - name: start web flags
    systemd: name=cs.web state=started

- hosts: checkers
  tasks:
  - name: start checkers
    systemd: name="cs.worker-checkers@{{ item }}" state=started
    with_sequence: count={{ cs_worker_instance }}
