env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/indent':
    - error
    - 4
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/member-delimiter-style':
    - error
  '@typescript-eslint/semi':
    - error
    - always
    - omitLastInOneLineBlock: true
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/consistent-type-imports':
    - error
    - fixStyle: inline-type-imports
  '@typescript-eslint/space-infix-ops':
    - error
  no-trailing-spaces:
    - error
  no-multi-spaces:
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
  linebreak-style:
    - error
    - unix
  sort-imports:
    - error
    - ignoreDeclarationSort: true
