version: '2.2'
services:
  example:
    build: .
    restart: "always"
    stop_grace_period: 1s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 80
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    ports:
      - "2222:2222"

