- name: systemd config
  template: src=cs.manager.service.j2 dest=/etc/systemd/system/cs.manager.service
  notify:
    - reload systemd
  tags: update

- name: systemd config
  template: src=cs.worker-default.service.j2 dest=/etc/systemd/system/cs.worker-default.service
  notify:
    - reload systemd
  tags: update
