services:
  hermicache:
    build:
      context: .
    restart: always
    entrypoint: julia
    command: Server.jl
    depends_on:
      - redis
    mem_limit: 1G
    memswap_limit: 1G
    cpu_count: 1
    pids_limit: 128
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    ports:
      - 8080:8080
  redis:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    hostname: redis
    volumes:
      - vault:/vault/books
    mem_limit: 1G
    memswap_limit: 1G
    cpu_count: 1
    pids_limit: 128
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
volumes:
  vault:

