- hosts: checkers
  roles:
    - update_cs_config
    - deploy_checkers

- hosts: checkers
  tasks:
  - name: Download bookster static
    ansible.builtin.get_url:
      url: https://bookster-staff.ams3.digitaloceanspaces.com/data.tar
      dest: "{{ cs_dir }}/checkers/bookster/"
      owner: "{{ cs_user }}"
      group: "{{ cs_user }}"
  - name: Extract bookster static
    ansible.builtin.unarchive:
      remote_src: true
      src: "{{ cs_dir }}/checkers/bookster/data.tar"
      dest: "{{ cs_dir }}/checkers/bookster/"

- hosts: checkers
  tasks:
    - name: stop checkers
      systemd: name="cs.worker-checkers@{{ item }}" state=stopped
      with_sequence: count={{ cs_worker_instance }}

- hosts: checkers
  tasks:
    - name: start checkers
      systemd: name="cs.worker-checkers@{{ item }}" state=started
      with_sequence: count={{ cs_worker_instance }}