- name: apt keys
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: install

- name: pg repo source
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    filename: pgdg
    validate_certs: no
  tags: install

- name: pg install
  apt: name=postgresql-13 state=latest update_cache=yes
  tags: install

- name: pg user
  shell: psql -c "create role {{ pg_cs_user }} login password '{{ pg_cs_pass }}'"
  become: true
  become_user: postgres
  register: r
  failed_when: r.rc > 1
  changed_when: "'CREATE ROLE' in r.stdout"

- name: pg db
  shell: createdb -O {{ pg_cs_user }} {{ pg_cs_db }}
  become: true
  become_user: postgres
  register: r
  failed_when: r.rc > 1
  changed_when: r.rc == 0

- name: pg stat statements
  shell: psql {{ pg_cs_db }} -c "create extension pg_stat_statements"
  become: true
  become_user: postgres
  register: r
  failed_when: r.rc > 1
  changed_when: "'CREATE EXTENSION' in r.stdout"

- name: pg config
  template: src=pg_cs.conf.j2 dest=/etc/postgresql/13/main/conf.d/cs.conf
  notify:
    - restart postgresql
  tags: install

- name: pg_hba config
  lineinfile:
    path: /etc/postgresql/13/main/pg_hba.conf
    insertafter: '^# IPv4 local connections:'
    regexp: '^host\tcs'
    line: "host\tcs\tcs\t0.0.0.0/0\tmd5"
  notify:
    - restart postgresql
  tags: install
