
name: Check dcs
on:
  push:
    branches:
      - master
    paths:
      - 'services/dcs/**'
      - 'checkers/dcs/**'
      - 'sploits/dcs/**'
  workflow_dispatch:
    inputs:
      cleanup_before_deploy:
        description: 'Stops and fully removes service (with volumes!) before deploying again. Type "yes" to do it.'
        required: false
        default: "no"
jobs:
  check_service_dcs:
    name: Check service dcs
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/dcs/before_image_build.sh ]; then (cd ./services/dcs && ./before_image_build.sh); fi
    - name: Setup dcs
      run: (cd ./services/dcs && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_dcs:
    name: Check checker dcs
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/dcs/before_image_build.sh ]; then (cd ./services/dcs && ./before_image_build.sh); fi
    - name: Setup dcs
      run: (cd ./services/dcs && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/dcs/requirements.txt ]; then python -m pip install -r checkers/dcs/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/dcs && ./dcs.checker.py TEST 127.0.0.1)
  check_sploit_dcs:
    name: Check sploit dcs
    runs-on: ubuntu-20.04
    if: ${{ false }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/dcs/before_image_build.sh ]; then (cd ./services/dcs && ./before_image_build.sh); fi
    - name: Setup dcs
      run: (cd ./services/dcs && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/dcs/requirements.txt ]; then python -m pip install -r checkers/dcs/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/dcs/requirements.txt ]; then python -m pip install -r sploits/dcs/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check-sploit.py dcs)
  update_dcs:
    name: Deploy service using ansible to first teams
    needs: [check_service_dcs, check_checker_dcs, check_sploit_dcs]
    runs-on: self-hosted
    if: ${{ false }} # disable on game just in case
    steps:
    #- name: install ansible
    #  run: sudo apt-get install -y ansible
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: change permission for ssh key
      run: chmod 0600 ./teams/for_devs.ssh_key
    - name: Run prebuilt hook
      run: if [ -f services/dcs/before_image_build.sh ]; then (cd ./services/dcs && sudo ./before_image_build.sh); fi
    - name: update checkers
      run: cd ./ansible && ansible-playbook cs-checkers.yml
    - name: deploy dcs
      run: cd ./ansible && ansible-playbook --extra-vars cleanup_service=${{ github.event.inputs.cleanup_before_deploy }} -t dcs -l dcs deploy-services.yml
