
name: Check stalker
on:
  push:
    branches:
      - master
    paths:
      - 'services/stalker/**'
      - 'checkers/stalker/**'
      - 'sploits/stalker/**'
  workflow_dispatch:
    inputs:
      cleanup_before_deploy:
        description: 'Stops and fully removes service (with volumes!) before deploying again. Type "yes" to do it.'
        required: false
        default: "no"
jobs:
  check_service_stalker:
    name: Check service stalker
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/stalker/before_image_build.sh ]; then (cd ./services/stalker && ./before_image_build.sh); fi
    - name: Setup stalker
      run: (cd ./services/stalker && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_stalker:
    name: Check checker stalker
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/stalker/before_image_build.sh ]; then (cd ./services/stalker && ./before_image_build.sh); fi
    - name: Setup stalker
      run: (cd ./services/stalker && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/stalker/requirements.txt ]; then python -m pip install -r checkers/stalker/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/stalker && ./stalker.checker.py TEST 127.0.0.1)
  check_sploit_stalker:
    name: Check sploit stalker
    runs-on: ubuntu-20.04
    if: ${{ false }} # do not check sploits
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/stalker/before_image_build.sh ]; then (cd ./services/stalker && ./before_image_build.sh); fi
    - name: Setup stalker
      run: (cd ./services/stalker && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/stalker/requirements.txt ]; then python -m pip install -r checkers/stalker/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/stalker/requirements.txt ]; then python -m pip install -r sploits/stalker/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check-sploit.py stalker)
  update_stalker:
    name: Deploy service using ansible to first teams
    needs: [check_service_stalker, check_checker_stalker, check_sploit_stalker]
    runs-on: self-hosted
    if: ${{ false }} # disable on game just in case
    steps:
    #- name: install ansible
    #  run: sudo apt-get install -y ansible
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: change permission for ssh key
      run: chmod 0600 ./teams/for_devs.ssh_key
    - name: Run prebuilt hook
      run: if [ -f services/stalker/before_image_build.sh ]; then (cd ./services/stalker && sudo ./before_image_build.sh); fi
    - name: update checkers
      run: cd ./ansible && ansible-playbook cs-checkers.yml
    - name: deploy stalker
      run: cd ./ansible && ansible-playbook --extra-vars cleanup_service=${{ github.event.inputs.cleanup_before_deploy }} -t stalker -l stalker deploy-services.yml
