
name: Check solaris
on:
  push:
    branches:
      - master
    paths:
      - 'services/solaris/**'
      - 'checkers/solaris/**'
      - 'sploits/solaris/**'
  workflow_dispatch:
    inputs:
      cleanup_before_deploy:
        description: 'Stops and fully removes service (with volumes!) before deploying again. Type "yes" to do it.'
        required: false
        default: "no"
jobs:
  check_service_solaris:
    name: Check service solaris
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/solaris/before_image_build.sh ]; then (cd ./services/solaris && ./before_image_build.sh); fi
    - name: Setup solaris
      run: (cd ./services/solaris && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_solaris:
    name: Check checker solaris
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/solaris/before_image_build.sh ]; then (cd ./services/solaris && ./before_image_build.sh); fi
    - name: Setup solaris
      run: (cd ./services/solaris && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup checker libraries
      run: if [ -f checkers/solaris/requirements.txt ]; then python -m pip install -r checkers/solaris/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/solaris && ./solaris.checker.py TEST 127.0.0.1)
  check_sploit_solaris:
    name: Check sploit solaris
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run prebuilt hook
      run: if [ -f services/solaris/before_image_build.sh ]; then (cd ./services/solaris && ./before_image_build.sh); fi
    - name: Setup solaris
      run: (cd ./services/solaris && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup checker libraries
      run: if [ -f checkers/solaris/requirements.txt ]; then python -m pip install -r checkers/solaris/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/solaris/requirements.txt ]; then python -m pip install -r sploits/solaris/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check-sploit.py solaris)
  update_solaris:
    name: Deploy service using ansible to first teams
    needs: [check_service_solaris, check_checker_solaris, check_sploit_solaris]
    runs-on: self-hosted
    if: ${{ false }} # disable on game just in case
    steps:
    #- name: install ansible
    #  run: sudo apt-get install -y ansible
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: change permission for ssh key
      run: chmod 0600 ./teams/for_devs.ssh_key
    - name: Run prebuilt hook
      run: if [ -f services/solaris/before_image_build.sh ]; then (cd ./services/solaris && sudo ./before_image_build.sh); fi
    - name: update checkers
      run: cd ./ansible && ansible-playbook cs-checkers.yml
    - name: deploy solaris
      run: cd ./ansible && ansible-playbook --extra-vars cleanup_service=${{ github.event.inputs.cleanup_before_deploy }} -t solaris -l solaris deploy-services.yml
