
name: Check bookster
on:
  push:
    branches:
      - master
    paths:
      - 'services/bookster/**'
      - 'checkers/bookster/**'
      - 'sploits/bookster/**'
  workflow_dispatch:
    inputs:
      cleanup_before_deploy:
        description: 'Stops and fully removes service (with volumes!) before deploying again. Type "yes" to do it.'
        required: false
        default: "no"
jobs:
  check_service_bookster:
    name: Check service bookster
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Run prebuilt hook
      run: if [ -f services/bookster/before_image_build.sh ]; then (cd ./services/bookster && ./before_image_build.sh); fi
    - name: Setup bookster
      run: (cd ./services/bookster && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_bookster:
    name: Check checker bookster
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Run prebuilt hook
      run: if [ -f services/bookster/before_image_build.sh ]; then (cd ./services/bookster && ./before_image_build.sh); fi
    - name: Setup bookster
      run: (cd ./services/bookster && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/bookster/requirements.txt ]; then python -m pip install -r checkers/bookster/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/bookster && ./bookster.checker.py TEST 127.0.0.1)
  check_sploit_bookster:
    name: Check sploit bookster
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Run prebuilt hook
      run: if [ -f services/bookster/before_image_build.sh ]; then (cd ./services/bookster && ./before_image_build.sh); fi
    - name: Setup bookster
      run: (cd ./services/bookster && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/bookster/requirements.txt ]; then python -m pip install -r checkers/bookster/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/bookster/requirements.txt ]; then python -m pip install -r sploits/bookster/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check-sploit.py bookster)
  update_bookster:
    name: Deploy service using ansible to first teams
    needs: [check_service_bookster, check_checker_bookster, check_sploit_bookster]
    runs-on: self-hosted
    if: ${{ false }} # disable on game just in case
    steps:
    #- name: install ansible
    #  run: sudo apt-get install -y ansible
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: change permission for ssh key
      run: chmod 0600 ./teams/for_devs.ssh_key
    - name: Run prebuilt hook
      run: if [ -f services/bookster/before_image_build.sh ]; then (cd ./services/bookster && sudo ./before_image_build.sh); fi
    - name: update checkers
      run: cd ./ansible && ansible-playbook cs-checkers.yml
    - name: deploy bookster
      run: cd ./ansible && ansible-playbook --extra-vars cleanup_service=${{ github.event.inputs.cleanup_before_deploy }} -t bookster -l bookster deploy-services.yml
