name: Deploy checkers
on:
  workflow_dispatch: {}

jobs:
  rebuild_image:
    name: Deploy checkers
    runs-on: self-hosted

    steps:
    - name: Checkout infra
      uses: actions/checkout@v2
    - name: fix ssh-key permissions
      run: (cd ansible/cs && chmod 600 .keys/cs_key)
    - name: deploy checkers
      run: (cd ansible/cs && ansible-playbook --private-key .keys/cs_key cs-checkers.yml)