name: Reset game
on:
  workflow_dispatch: {}

jobs:
  rebuild_image:
    name: Reset game
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: fix ssh-key permissions
      run: (cd ansible/cs && chmod 600 .keys/cs_key)
    - name: stop cs
      run: (cd ansible/cs && ansible-playbook --private-key .keys/cs_key cs-stop.yml)
    - name: reset cs
      run: (cd ansible/cs && ansible-playbook --private-key .keys/cs_key cs-init.yml)
    - name: start cs
      run: (cd ansible/cs && ansible-playbook --private-key .keys/cs_key cs-start.yml)